name: Compile projects
on:
  push:
    paths:
      - ".github/workflows/compile-sketch.yml"
      - "read_weather_data/**"
      - "DHT22/**"
  pull_request:
    paths:
      - ".github/workflows/compile-sketch.yml"
      - "read_weather_data/**"
      - "DHT22/**"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
            libraries: |
              - name: WiFiNINA
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:samd:mkr1000
            platforms: |
              - name: arduino:samd
            libraries: |
              - name: WiFi101
            artifact-name-suffix: arduino-samd-mkr1000
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
            libraries: |
              - name: WiFiNINA
            artifact-name-suffix: arduino-samd-nano_33_iot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            ${{ matrix.board.libraries }}
            - name: DHT sensor library
            - name: Adafruit Unified Sensor
            - name: Adafruit BME280
            - name: ArduinoMqttClient
            - name: NTPClient
            - name: RTCZero
          sketch-paths: |
            - "read_weather_data"
            - "DHT22"
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
